docs: Output Format
Raphtory/Raphtory pull request #250
Opened 2022-03-03 15:27 UTC by rutujasurve94

Docstring for `output` formatter

2022-03-03 18:00 UTC, ljeub-pometry commented on src/main/scala/com/raphtory/output/FileOutputFormat.scala
> +  */
a ` ```{seealso}``` ` section would be nice pointing to the Raphtory Query API and the OutputFormat base class

2022-03-04 12:47 UTC, rutujasurve94 commented on src/main/scala/com/raphtory/core/algorithm/OutputFormat.scala
> +  */
I've removed documentation for the abstract class for clarity 👍

2022-03-10 09:17 UTC, ljeub-pometry requested changes
This still has broken formatting, please fix and actually compile the documentation to check the output!

2022-03-10 09:17 UTC, ljeub-pometry commented on src/main/scala/com/raphtory/output/FileOutputFormat.scala
> +  * graph.pointQuery(EdgeList(), outputFormat, 1595303181, List())
Please implement the changes from the other pull request here as well, i.e., no need to have `setSpout` etc. functions, no schemas, `Raphtory.createTypedGraph` no longer exists...

2022-03-10 09:17 UTC, ljeub-pometry commented on src/main/scala/com/raphtory/output/FileOutputFormat.scala
> +  *  [](com.raphtory.core.client.RaphtoryClient)
I would add `[](com.raphtory.core.client.RaphtoryGraph)` and `[](com.raphtory.core.deploy.Raphtory)` as well

2022-03-10 09:17 UTC, ljeub-pometry commented on src/main/scala/com/raphtory/output/PulsarOutputFormat.scala
> +  * graph.pointQuery(EdgeList(), outputFormat, 1595303181, List())
Same as for FileOutputFormat

2022-03-10 09:17 UTC, ljeub-pometry commented on src/main/scala/com/raphtory/output/PulsarOutputFormat.scala
> +  * Reference: [](com.raphtory.core.algorithm.OutputFormat)
This is indented wrong and missing blank lines, does not format correctly when compiled. Can you please check the output after fixing this!

2022-03-10 09:17 UTC, ljeub-pometry commented on src/main/scala/com/raphtory/output/PulsarOutputFormat.scala
> +  *  [](com.raphtory.core.client.RaphtoryClient.PointQuery)
Second link does not exist, probably just copy from FileOutputFormat

2022-03-10 09:17 UTC, ljeub-pometry commented on src/main/scala/com/raphtory/output/FileOutputFormat.scala
> +  *   Reference: [](com.raphtory.core.algorithm.OutputFormat)
This is not indented correctly and thus does not produce the expected output, please check!

2022-03-11 10:26 UTC, ljeub-pometry approved these changes

2022-03-11 10:26 UTC, merged