docs: Raphtory Deploy
Raphtory/Raphtory pull request #261
Opened 2022-03-08 16:22 UTC by rutujasurve94

Docs for Raphtory Deploy:

- [ ] `RaphtoryService`
- [ ] `Raphtory`

2022-03-11 15:17 UTC, Haaroon requested changes

2022-03-11 15:17 UTC, Haaroon commented on src/main/scala/com/raphtory/core/deploy/Raphtory.scala
> +  *    : Create Spout
Yes this creates a spout, as the name suggests, but what kind of spout class can you give to this? any examples? what does this spout do?

2022-03-11 15:17 UTC, Haaroon commented on src/main/scala/com/raphtory/core/deploy/Raphtory.scala
> +  *    : Create Graph Builder
same comment as the spout, any examples of graph builders? what does a graph builder actually do?  where is the graph builder used?

2022-03-11 15:17 UTC, Haaroon commented on src/main/scala/com/raphtory/core/deploy/Raphtory.scala
> +  *    : Creates Partition Manager
what is a parition manager exactly? where is it used? what does it do? what type is returned?

2022-03-11 15:17 UTC, Haaroon commented on src/main/scala/com/raphtory/core/deploy/Raphtory.scala
> +  *    : Creates Query Manager
what is a query manager exactly? where is it used? what does it do? what type is returned?

2022-03-11 15:17 UTC, Haaroon commented on src/main/scala/com/raphtory/core/deploy/Raphtory.scala
> +  *    : Returns default config
what is the default config? where is that located? what kind of custom config can we use? can we have an example of what a custom config is?

2022-03-11 15:17 UTC, Haaroon commented on src/main/scala/com/raphtory/core/deploy/Raphtory.scala
> +  *    : Returns Config
the conf builder is pretty important, its used almost everywhere, can we please explain where is the config this returns? how is that generated? what kind of custom config can we use? can we have an example of what a custom config is?

2022-03-11 15:17 UTC, Haaroon commented on src/main/scala/com/raphtory/core/deploy/Raphtory.scala
> +  *    : Create spout executor
what is a spout executor? what does it do?

2022-03-11 15:17 UTC, Haaroon commented on src/main/scala/com/raphtory/core/deploy/Raphtory.scala
> +  *    : Create Graph using spout, graph-builder and custom config
What kind of object does this return? what can we do with that object? 
What goes in the custom config are there any examples? what can we do with this client object that this creates?

2022-03-11 15:17 UTC, Haaroon commented on src/main/scala/com/raphtory/core/deploy/RaphtoryService.scala
> +  *  : `RaphtoryService` for initialising spout, graphbuilder, deploying spout, partition and query manager
this is actually an abstract class, that has its some of its functions implemented later on within the code base, this doc should talk about this, what does this service do? examples of where it is used?  alot of our examples extend this class and add functionality, its one of the core components, the current description does not mention this

2022-03-11 15:17 UTC, Haaroon commented on src/main/scala/com/raphtory/core/deploy/RaphtoryService.scala
> +  *      : Initialise Spout
this is an abstract method, any examples of how it is overridden when the class is extended? for example you could say the defineSpout is a function that is overriden by objects that extend the raphtory service, this is used to construct the spout which is used to ingest data. an example of ovveriding this fn is as follows. e.g.

2022-03-11 15:17 UTC, Haaroon commented on src/main/scala/com/raphtory/core/deploy/RaphtoryService.scala
> +  *      : Initialise GraphBuilder
see my spout comment

2022-03-11 15:17 UTC, Haaroon commented on src/main/scala/com/raphtory/core/deploy/RaphtoryService.scala
> +  *      : Deploy spout
yes this deploys the spout, but how? what function does it call? where does it get the spout from?

2022-03-11 15:17 UTC, Haaroon commented on src/main/scala/com/raphtory/core/deploy/RaphtoryService.scala
> +  *      : Deploy builder
see deploy spout comment

2022-03-11 15:17 UTC, Haaroon commented on src/main/scala/com/raphtory/core/deploy/RaphtoryService.scala
> +  *      : Deploy partition
see deploy spout comment

2022-03-11 15:17 UTC, Haaroon commented on src/main/scala/com/raphtory/core/deploy/RaphtoryService.scala
> +  *      : Deploy query manager
see deploy spout comment

2022-03-14 09:18 UTC, rutujasurve94 commented
Thanks a lot for the detailed review @Haaroon , I've updated the documentation accordingly to be very much in depth for ease of onboarding new developers to Raphtory.

2022-03-15 10:00 UTC, merged