Feature/exploded vertex
Raphtory/Raphtory pull request #342
Opened 2022-04-06 08:44 UTC by ljeub-pometry

Done:
- Implements multilayer view
- History is now deduplicated and sorted
- VertexID is a generic type to suport tuple IDs
- Boolean accumulators

TODO:
- Still needs documentation
- Some default interlayer edge builders
- Rewiring of multilayer edges for more interesting views

2022-04-08 11:18 UTC, ljeub-pometry commented
- Improved switching between views
- Default interlayer edge builders

2022-04-08 13:51 UTC, ljeub-pometry commented
Added some rudimentary documentation of the new methods, would be good to get some feedback on this

2022-04-11 08:13 UTC, ljeub-pometry commented
Note, pulsar output failed with error `raphtoryTest` does not exist

2022-04-11 10:39 UTC, ljeub-pometry commented
Only includes underlying implementation of ExplodedVertex and related functionality for multilayer views. Public API is commented out for now until GraphPerspective implementations for the different views are cleaned up.

2022-04-12 08:54 UTC, ricopinazo commented
The changes to the API and the documentation were looking good. I assume we can review this when we introduce the changes to the classes you mention in a future PR.

2022-04-12 12:40 UTC, miratepuffin requested changes
Just need to make a couple of changes with the vertex iterator and this is all good to go. May also be worth us considering renaming/changing the potion of the VertexID as it's only Longs for the current release and may cause some confusion in the algorithms. Can do this as a separate PR though before the final Jar creation.

2022-04-12 14:08 UTC, ljeub-pometry commented on core/src/main/scala/com/raphtory/storage/pojograph/PojoGraphLens.scala
> +      vertices.iterator.flatMap(_.explodedVertices)
iterator.flatMap is lazy

2022-04-12 14:09 UTC, ljeub-pometry commented on core/src/main/scala/com/raphtory/storage/pojograph/PojoGraphLens.scala
> +    var count: Int = 0
iterator.size is inefficient

2022-04-12 14:18 UTC, ljeub-pometry commented on core/src/main/scala/com/raphtory/storage/pojograph/entities/internal/PojoEntity.scala
> +    history sortedAppend ((msgTime, false))
Revisit when improving support for deletions

2022-04-12 14:18 UTC, ljeub-pometry commented on core/src/main/scala/com/raphtory/storage/pojograph/entities/internal/PojoEntity.scala
> +        case InsertionPoint(i) => history(i - 1)
This should be done in a few more places

2022-04-12 14:23 UTC, ljeub-pometry commented on core/src/test/scala/com/raphtory/lotrtest/LotrTest.scala
> +    val expected = "c21170ae40544156af69000d2b0d6e8eaf5f593d3905810c7527f2e09b8e9172"
This has changed because of deduplication

2022-04-13 08:36 UTC, ljeub-pometry commented on core/src/main/scala/com/raphtory/algorithms/generic/EdgeList.scala
> +        val neighbourMap = vertex.getState[Map[vertex.VertexID, String]]("neighbourNames")
Renamed `VertexID` to `IDType` but keeping changes in this pull request as reworking this is difficult

2022-04-13 11:13 UTC, miratepuffin approved these changes

2022-04-13 11:13 UTC, merged