SourceTrackers explicit blocking
Raphtory/Raphtory pull request #547
Opened 2022-08-30 17:57 UTC by miratepuffin

2022-08-31 15:14 UTC, miratepuffin commented
Have now added a different fix for the client to block until its own messages have been sent. Have tested with sending two sets of updates and queries in-between

![image](https://user-images.githubusercontent.com/6665739/187709547-2b6e5bca-958a-4dbe-bff4-971639472fb1.png)

```
15:50:00.365 [io-compute-2] INFO  com.raphtory.internals.components.partition.PartitionOrchestrator$ - Creating '1' Partition Managers for 'conventional_baby-blue_muskox'.
15:50:01.752 [io-compute-6] INFO  com.raphtory.internals.components.partition.PartitionManager - Partition 0: Starting partition manager for 'conventional_baby-blue_muskox'.
15:50:03.026 [spawner-akka.actor.default-dispatcher-3] INFO  com.raphtory.internals.components.querymanager.QueryManager - Source '0' is unblocking analysis for Graph 'conventional_baby-blue_muskox' with 7947 messages sent.
15:50:03.167 [io-compute-7] INFO  com.raphtory.api.querytracker.QueryProgressTracker - Job ConnectedComponents_4389634494061553108: Starting query progress tracker.
15:50:03.179 [spawner-akka.actor.default-dispatcher-3] INFO  com.raphtory.internals.components.querymanager.QueryManager - Query 'ConnectedComponents_4389634494061553108' currently blocked, waiting for ingestion to complete.
15:50:03.345 [spawner-akka.actor.default-dispatcher-3] INFO  com.raphtory.internals.components.querymanager.QueryManager - Query 'ConnectedComponents_4389634494061553108' received, your job ID is 'ConnectedComponents_4389634494061553108'.
15:50:03.362 [spawner-akka.actor.default-dispatcher-3] INFO  com.raphtory.internals.components.partition.QueryExecutor - ConnectedComponents_4389634494061553108_0: Starting QueryExecutor.
15:50:03.611 [spawner-akka.actor.default-dispatcher-10] INFO  com.raphtory.internals.components.querymanager.QueryHandler - Job 'ConnectedComponents_4389634494061553108': Perspective at Time '32674' took 234 ms to run. 
15:50:03.612 [spawner-akka.actor.default-dispatcher-7] INFO  com.raphtory.api.querytracker.QueryProgressTracker - Job 'ConnectedComponents_4389634494061553108': Perspective '32674' finished in 446 ms.
15:50:03.612 [spawner-akka.actor.default-dispatcher-7] INFO  com.raphtory.api.querytracker.QueryProgressTracker - Job ConnectedComponents_4389634494061553108: Running query, processed 1 perspectives.
15:50:03.615 [spawner-akka.actor.default-dispatcher-7] INFO  com.raphtory.api.querytracker.QueryProgressTracker - Job ConnectedComponents_4389634494061553108: Query completed with 1 perspectives and finished in 449 ms.
15:50:04.951 [spawner-akka.actor.default-dispatcher-10] INFO  com.raphtory.internals.components.querymanager.QueryManager - Source '0' is unblocking analysis for Graph 'conventional_baby-blue_muskox' with 15894 messages sent.
15:50:04.960 [io-compute-4] INFO  com.raphtory.api.querytracker.QueryProgressTracker - Job Degree_5320277040710172637: Starting query progress tracker.
15:50:04.979 [spawner-akka.actor.default-dispatcher-10] INFO  com.raphtory.internals.components.querymanager.QueryManager - Query 'Degree_5320277040710172637' currently blocked, waiting for ingestion to complete.
15:50:05.160 [spawner-akka.actor.default-dispatcher-10] INFO  com.raphtory.internals.components.querymanager.QueryManager - Query 'Degree_5320277040710172637' received, your job ID is 'Degree_5320277040710172637'.
15:50:05.162 [spawner-akka.actor.default-dispatcher-10] INFO  com.raphtory.internals.components.partition.QueryExecutor - Degree_5320277040710172637_0: Starting QueryExecutor.
15:50:05.214 [spawner-akka.actor.default-dispatcher-10] INFO  com.raphtory.internals.components.querymanager.QueryHandler - Job 'Degree_5320277040710172637': Perspective at Time '32674' took 49 ms to run. 
15:50:05.214 [spawner-akka.actor.default-dispatcher-11] INFO  com.raphtory.api.querytracker.QueryProgressTracker - Job 'Degree_5320277040710172637': Perspective '32674' finished in 254 ms.
15:50:05.215 [spawner-akka.actor.default-dispatcher-11] INFO  com.raphtory.api.querytracker.QueryProgressTracker - Job Degree_5320277040710172637: Running query, processed 1 perspectives.
15:50:05.215 [spawner-akka.actor.default-dispatcher-11] INFO  com.raphtory.api.querytracker.QueryProgressTracker - Job Degree_5320277040710172637: Query completed with 1 perspectives and finished in 255 ms.
```

2022-08-31 17:13 UTC, ljeub-pometry commented on core/src/main/scala/com/raphtory/internals/management/QuerySender.scala
>      val jobName     = if (customJobName.nonEmpty) customJobName else getDefaultName(query)
This creates a race condition in the case of multiple sets of updates and queries. We need to integrate the unblock information into the query message itself.

2022-08-31 17:14 UTC, ljeub-pometry requested changes
Has a race condition for the auto blocking

2022-09-02 08:32 UTC, ljeub-pometry approved these changes
Could simplify a little but looks like it should work

2022-09-02 08:32 UTC, ljeub-pometry commented on core/src/main/scala/com/raphtory/internals/management/QuerySender.scala
> -    if (lastQueryIndex < individualUpdateIndex) {
could just check for `indexSinceLastIDChange > 0` and remove `lastQueryIndex` (one less thing to keep track of)

2022-09-02 08:32 UTC, ljeub-pometry commented on core/src/main/scala/com/raphtory/internals/management/QuerySender.scala
> +            currentSourceID == -1 || (update && newIDRequiredOnUpdate)
`newIDRequiredOnUpdate == (indexSinceLastIDChange == 0)`

could do everything using only `indexSinceLastIDChange` and `totalUpdateIndex` not sure if it is a good idea though

2022-09-02 17:54 UTC, merged