Implemented HITS algorithm (hubs and authorities)
Raphtory/Raphtory pull request #557
Opened 2022-09-05 12:20 UTC by nrs1729

The algorithm is working but the tests still need updating.

2022-09-05 15:09 UTC, Alnaimi- commented on core/src/main/scala/com/raphtory/algorithms/generic/HITS.scala
> +                if (Math.abs(currHub - newHub) < 0.00001 & Math.abs(currAuth - newAuth) < 0.00001)
Can you make the `0.00001` as a default parameter please.

2022-09-07 11:22 UTC, ljeub-pometry requested changes
Algorithm looks good. I've opened a pull request for doing floating-point comparison tests (#565). Once that is in, you can remove the truncate option.
The documentation needs some minor fixes and this should be good to merge.

2022-09-07 11:22 UTC, ljeub-pometry commented on core/src/main/scala/com/raphtory/algorithms/generic/HITS.scala
> +        }
See #565

2022-10-27 13:42 UTC, ljeub-pometry approved these changes
Looks good, ready to merge

2022-10-27 13:42 UTC, merged