submit Assortativity
Raphtory/Raphtory pull request #672
Opened 2022-11-09 09:00 UTC by Peijie-Zhong

### This pull request edits the assortativity algorithm

2022-11-11 13:41 UTC, Haaroon commented
Hi, if you can please add a test for this and then we can approve.

2022-11-11 13:42 UTC, Haaroon requested changes
Needs a test

2022-11-11 14:34 UTC, Peijie-Zhong commented
> 

Hi Haaroon, I've updated a test case. Could you please check if it's OK? Thanks

2022-11-13 15:38 UTC, miratepuffin approved these changes

2022-11-13 15:39 UTC, merged