impl disruptor based pojo partition
Raphtory/Raphtory pull request #766
Opened 2023-01-05 15:09 UTC by iamsmkr

### What changes were proposed in this pull request?
Disruptor pattern implementation of PojoBasedPartition

### Why are the changes needed?
PojoBasedPartition implementation was single threaded. We have changed it to disruptor based multi-threaded implementation.

### Does this PR introduce any user-facing change? If yes is this documented?
No

### How was this patch tested?
Unit, Integration tests

### Are there any further changes required?
No

2023-01-06 18:21 UTC, miratepuffin requested changes

2023-01-06 18:21 UTC, miratepuffin commented on core/src/main/scala/com/raphtory/internals/storage/pojograph/DisruptorQueue.scala
> +      if (event.dstId == -1L) addVertex(event) else addEdge(event)
Ok don't do this, but please add comments

2023-01-06 18:21 UTC, miratepuffin commented on core/src/main/scala/com/raphtory/internals/storage/pojograph/DisruptorQueue.scala
> +          logger.trace(s"History point added to vertex: $srcId")
Combine these and the one below.

2023-01-06 18:21 UTC, miratepuffin commented on core/src/main/scala/com/raphtory/internals/storage/pojograph/DisruptorQueue.scala
> +        case LocalEdge            => addLocalEdge(event)
c>()->()

2023-01-06 18:21 UTC, miratepuffin commented on core/src/main/scala/com/raphtory/internals/storage/pojograph/DisruptorQueue.scala
> +          edge.setType(edgeType.map(_.name))
If you are reviving we do not need to set the type

2023-01-06 18:21 UTC, miratepuffin commented on core/src/main/scala/com/raphtory/internals/storage/pojograph/DisruptorQueue.scala
> +    (0 until N_LOAD_THREADS).foreach(i => disruptors(i).halt())
We do not need to halt the disruptors -- as per our conversation

2023-01-06 18:21 UTC, miratepuffin commented on core/src/main/scala/com/raphtory/internals/storage/pojograph/DisruptorQueue.scala
> +      private[pojograph] var vertexType: Option[Type] = None,
I think these two can be merged

2023-01-09 10:20 UTC, iamsmkr commented on core/src/main/scala/com/raphtory/internals/storage/pojograph/DisruptorQueue.scala
> +    final val EVENT_FACTORY =
This won't work. Disruptors are based on Fly Weight pattern instead.

2023-01-09 10:42 UTC, iamsmkr commented on core/src/main/scala/com/raphtory/internals/storage/pojograph/DisruptorQueue.scala
> +      val srcVertex = getVerticesMap(srcId)(srcId)
getVerticesMap(srcId) is being used in a lot other places. Combining them would require another method which is more code

2023-01-12 13:47 UTC, ljeub-pometry submitted a review, later dismissed
Remove the println and turn into a log message and this should be good to merge

2023-01-12 15:18 UTC, miratepuffin approved these changes

2023-01-12 15:18 UTC, merged